# Generated by Django 3.0.8 on 2021-01-20 14:31

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=30)),
                ('address_line_2', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('zipcode', models.IntegerField()),
                ('country', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('username', models.EmailField(max_length=250)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('alternate_mobile_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('addresses', models.ManyToManyField(to='loginapp.ShippingAddress')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.User')),
            ],
        ),
    ]
