# Generated by Django 3.0.8 on 2021-01-22 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('brand', models.CharField(choices=[('puma', 'Puma'), ('adidas', 'Adidas'), ('woodland', 'Woodland')], max_length=10)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('sneakers', 'Sneakers'), ('loafers', 'Loafers'), ('oxfords', 'Oxfords')], max_length=10)),
                ('availibility', models.IntegerField()),
            ],
        ),
    ]
