# Generated by Django 3.0.8 on 2021-01-22 08:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loginapp', '0003_auto_20210121_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', django.contrib.postgres.fields.jsonb.JSONField()),
                ('totalPrice', models.FloatField()),
                ('orderDate', models.DateField(null=True)),
                ('orderstatus', models.CharField(max_length=50, null=True)),
                ('paymentstatus', models.CharField(max_length=50, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginapp.User')),
            ],
        ),
    ]
